env:
- COVERAGE: true
cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
before_install:
- echo "MAVEN_OPTS='-Xmx256m'" > ~/.mavenrc
- curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/dangernoodle-io/artifact-version-recorder/master/src/main/travis/settings.xml
script:
- mvn -V -B verify jacoco:report coveralls:report
notifications:
  email: false
  slack:
    rooms:
      secure: FImeXF6fFtm6EbJYU49Z3M/pGxu5ZxM+VafDvEaTUP9OoyPhh2MlsRZdOpxJJQ7hqssyCSFbtCh6q8DGrjRnMg0T4uglmIY5Yo+uPMAXP10wLbXnVepyvmfWEBr1D3J8seuOK/YAnkSqqstb3dVGkmvbK9RIrqpoXG5sQCEWZbZtzBSI7sF/0gbKVJKQ4NmKzxYzhyc/RSiWoXyPKmYwebFmRF/S37TKAKUzsNpdXcvkWEIwnyaIvTiJ3TNT8tsS2rmajT97QJoRtSPQxydEb4q7RmcAUr9DRiPS59Mgndd9+8OsLGy2iDBnH1opoOdnzc9ovwW4QibNjpWre9s0N/4QfZTIVQ8YLb1H8kYk/uRXNZ7XUWtuF2pn3+O2DqTUtdYJDj0xy7OskzwCv3yF+7krmDmdWR3lCX+PoHy+cX3YbnNSlPcDCdrPgU2/ry459Li8NfyALqkaz+c7TZ7idh2ej32Dc0GpRpUA3BBg0QcWgofqLxzfVphbrdvzPT/qzgtTnn4ZDR8TWBE7H3fQdf/elqIyqVv8e5EUdl8Foq1s7O2z0cZFBaiRHcjCYtAEoFD1wWMbNbqN6qV3a+aQFPfd5GIXRyLoKFWb5q7ym9Bc1oXQ3iDWKxOPknDBWYwSrfgDh8hMUAphF+CSlqfPFDEL245ASGEB07Sxm/RVJCA=
